### ISSUE TITLE
Feature proposal - using an already parsed json

### ISSUE THREAD

**Issue by jesteracer** [dengyin2000/dynamic_widget#15]
First - Thank you for the library. 

A feature proposal: In my use case I already have a parsed json (using for my own widgets) and it will be helpful to have a method that will accept a map (not a jsonString) if it is already available in runtime.

**Comment by dengyin2000** [comment]
> First - Thank you for the library.
> 
> A feature proposal: In my use case I already have a parsed json (using for my own widgets) and it will be helpful to have a method that will accept a map (not a jsonString) if it is already available in runtime.

it already has the method, buildFromMap from dynamic_widget\lib\dynamic_widget.dart file.
