### ISSUE TITLE
onClicked should pass dynamic

### ISSUE THREAD

**Issue by eitanaviv** [dengyin2000/dynamic_widget#17]
I'm starting to use your library which is awesome and help me a lot, and I've been thinking that maybe onClicked in ClickListener should pass 'dynamic' rather than 'String' so we could pass custom objects or even map.
Thanks!

**Comment by dengyin2000** [comment]
> I'm starting to use your library which is awesome and help me a lot, and I've been thinking that maybe onClicked in ClickListener should pass 'dynamic' rather than 'String' so we could pass custom objects or even map.
> Thanks!

the design for dynamic widget is very simple, and onClick event is used for jumping to another page, so it would be a router, and it can be described by an uri, for example, "router://productDetailPage?pid=5566".

**Comment by eitanaviv** [comment]
Thank you!
