### ISSUE TITLE
dartpub analysis

### ISSUE THREAD

**Issue by neiljaywarner** [dengyin2000/dynamic_widget#2]
Could you please look into https://pub.dartlang.org/packages/dynamic_widget#-analysis-tab-
Some of them are easy wins - I'd love to see this package go from 65 score to 80 - you could get 9 just from a longer description

**Comment by dengyin2000** [comment]
> Could you please look into https://pub.dartlang.org/packages/dynamic_widget#-analysis-tab-
> Some of them are easy wins - I'd love to see this package go from 65 score to 80 - you could get 9 just from a longer description

thanks for your suggestion, I will fix them as soon as possible.
