### ISSUE TITLE
remote json

### ISSUE THREAD

**Issue by farukx** [dengyin2000/dynamic_widget#21]
Hi, @dengyin2000 How to read a remote JSON file ex:  https://raw.githubusercontent.com/farukx/Flutter-Dynamic-Widget/master/widget.json

**Comment by dengyin2000** [comment]
> Hi, @dengyin2000 How to read a remote JSON file ex: https://raw.githubusercontent.com/farukx/Flutter-Dynamic-Widget/master/widget.json

you can put it in a local file, or fetch it over network.
