### ISSUE TITLE
LICENSE needed

### ISSUE THREAD

**Issue by arimorty** [dengyin2000/dynamic_widget#22]
@dengyin2000 

Hi, great work!

I was thinking of creating a similar library, but hey, you already implemented most of what I had in mind. Is there a LICENSE for this library?

**Comment by dengyin2000** [comment]
> @dengyin2000
> 
> Hi, great work!
> 
> I was thinking of creating a similar library, but hey, you already implemented most of what I had in mind. Is there a LICENSE for this library?

license added.
