### ISSUE TITLE
Navigate routes

### ISSUE THREAD

**Issue by farukx** [dengyin2000/dynamic_widget#27]
How do I page detail a click_event route

 Navigator.pushNamed(context, '/second');

**Comment by dengyin2000** [comment]
Finally, pass the listener to build method.

  Future<Widget> _buildWidget() async{

    return DynamicWidgetBuilder().build(jsonString, buildContext, new DefaultClickListener());
  }

you should do the navigate in DefaultClickListener.

**Comment by farukx** [comment]
Hi my code gives error can you help me

https://paste.ubuntu.com/p/wYnttKrBzp/   
 
Another exception was thrown: setState() called in constructor: _Page2State#8fc5a(lifecycle state: created, no widget, not mounted)

**Comment by dengyin2000** [comment]
> Hi my code gives error can you help me
> 
> https://paste.ubuntu.com/p/wYnttKrBzp/
> 
> Another exception was thrown: setState() called in constructor: _Page2State#8fc5a(lifecycle state: created, no widget, not mounted)

I saw, your code should be wrong. You can't new a State object, because it was control by flutter widget lifecycle.

you want to share event2 variable in _Page2State and DefaultClickListener classes, you can use Provider flutter lib to share the event2 variable

**Comment by dengyin2000** [comment]
@farukx please see following code:

`import 'package:flutter/material.dart';
import 'package:dynamic_widget/dynamic_widget.dart';
import 'dart:async';

void main() => runApp(MyApp());

var page2State ;

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Dynamic Widget',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
          appBar: AppBar(
            title: Text("widget.title"),
          ),
          body: SafeArea(
            child: Row(
              children: <Widget>[
                Expanded(
                  child: Page2(),
                ),
                Expanded(
                  child: FutureBuilder<Widget>(
                    future: _buildWidget(context),
                    builder:
                        (BuildContext context, AsyncSnapshot<Widget> snapshot) {
                      if (snapshot.hasError) {
                        print(snapshot.error);
                      }
                      return snapshot.hasData
                          ? SizedBox.expand(
                        child: snapshot.data,
                      )
                          : Text("Loading...");
                    },
                  ),
                ),
              ],
            ),
          )),
    );
  }
}

class Page2 extends StatefulWidget {
  method(event) => createState().methodInPage2(event);

  @override
  _Page2State createState() => _Page2State();
}

class _Page2State extends State<Page2> {
  var event2;

  methodInPage2(event) {
    print("event2");
    setState(() {
      event2 = event;

    });
  }

  @override
  void initState() {
    // TODO: implement initState
    super.initState();
    page2State = this;
  }

  @override
  Widget build(BuildContext context) {
    return Container(
      child: Text(" event data  $event2"),
    );
  }
}

Future<Widget> _buildWidget(BuildContext context) async {
//print("object" +sabit.yenisablon);

  var gridList = '''
{
   "type":"Container",
   "alignment":"center",
   "child":{
      "type":"GridView",
      "crossAxisCount":2,
      "padding":"10, 10, 10, 10",
      "mainAxisSpacing":4.0,
      "crossAxisSpacing":4.0,
      "childAspectRatio":1.6,
      "children":[
         {
            "type":"RaisedButton",
            "padding":"8,8,8,8",
            "textColor":"#00FF00",
            "elevation":8.0,
            "splashColor":"#00FF00",
            "click_event":"number1",
            "child":{
               "type":"Text",
               "data":"1.buton"
            }
         },
         {
            "type":"RaisedButton",
            "padding":"8,8,8,8",
            "textColor":"#00FF00",
            "elevation":8.0,
            "splashColor":"#00FF00",
            "click_event":"number2",
            "child":{
               "type":"Text",
               "data":"2.buton"
            }
         },
         {
            "type":"RaisedButton",
            "padding":"8,8,8,8",
            "textColor":"#00FF00",
            "elevation":8.0,
            "splashColor":"#00FF00",
            "click_event":"number3",
            "child":{
               "type":"Text",
               "data":"2.buton"
            }
         }
      ]
   }
}

''';

  return DynamicWidgetBuilder()
      .build(gridList, context, new DefaultClickListener());
}

class DefaultClickListener implements ClickListener {
  BuildContext controller;

  @override
  onClicked(event) {
    print("event1: " + event);
    return page2State.methodInPage2(event);
  }
}`
