### ISSUE TITLE
[Spelling] Protocol is spelled "protocal" in readme.

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [dengyin2000/dynamic_widget#29]
> With this project, you can build your UIs from a json string, which is the UI **_protocal_**. The json string is very similar with the Flutter widget dart code. All widget type and widget properties are the same.

**Comment by dengyin2000** [comment]
thanks. I fixed it.

**Comment by ThinkDigitalSoftware** [comment]
You're welcome!
