### ISSUE TITLE
dynamic_widget_builder 用TypeScript编程方式构建dynamic_widget JSON

### ISSUE THREAD

**Issue by xioxin** [dengyin2000/dynamic_widget#30]
https://github.com/xioxin/dynamic_widget_builder

![image](https://user-images.githubusercontent.com/5716100/75900256-9f99d700-5e77-11ea-86e8-b09bb682eeb8.png)

**Comment by dengyin2000** [comment]
> https://github.com/xioxin/dynamic_widget_builder
> 
> ![image](https://user-images.githubusercontent.com/5716100/75900256-9f99d700-5e77-11ea-86e8-b09bb682eeb8.png)

你这个是用flutter代码  生成对应的json string？

**Comment by xioxin** [comment]
TypeScript 使用和flutter 相似的语法来构建json
