### ISSUE TITLE
项目中有大量的非空判断，是否可以简化？

### ISSUE THREAD

**Issue by freedom-shen** [dengyin2000/dynamic_widget#31]
例如：
``` dart
String clickEvent = map.containsKey("click_event") ? map['click_event'] : "";
// 等价
String clickEvent = map['click_event'] ?? '';
```

**Comment by freedom-shen** [comment]
在DynamicWidgetBuilder中放开了_parsers添加自定义的Widget的注册，buildFromMap中通过遍历查询，建议将List _parsers修改成为 Map<String, WidgetParser>提高效率

**Comment by dengyin2000** [comment]
> 例如：
> 
> ```dart
> String clickEvent = map.containsKey("click_event") ? map['click_event'] : "";
> // 等价
> String clickEvent = map['click_event'] ?? '';
> ```

嗯， 会修改下，从java转过来的。搞这个项目的时候其实dart语法都还不怎么熟悉。

**Comment by dengyin2000** [comment]
> 在DynamicWidgetBuilder中放开了_parsers添加自定义的Widget的注册，buildFromMap中通过遍历查询，建议将List _parsers修改成为 Map<String, WidgetParser>提高效率

谢谢， 很好的建议，随着widget parser的增多，这个效率肯定会有问题。下个版本解决。
