### ISSUE TITLE
Typo Documentation in ClipRRect Widget

### ISSUE THREAD

**Issue by CoderJava** [dengyin2000/dynamic_widget#35]
Hi, I found typo text in your documentation about ClipRRect Widget. 

> ClipRRect, here to see flutter **TextSpan** definition. Supported json properties:

You can check it in here
https://github.com/dengyin2000/dynamic_widget/blob/master/WIDGETS.md#cliprrect-widget

**Comment by dengyin2000** [comment]
Thanks, fixed

**Comment by CoderJava** [comment]
> Thanks, fixed

Ok.
