### ISSUE TITLE
showcase

### ISSUE THREAD

**Issue by neiljaywarner** [dengyin2000/dynamic_widget#4]
Is there a blog post or live app on the stores that use this, or live examples from the network?

This just really seems like it shows a lot of promise re: code push competition?
Thanks

**Comment by dengyin2000** [comment]
> Is there a blog post or live app on the stores that use this, or live examples from the network?
> 
> This just really seems like it shows a lot of promise re: code push competition?
> Thanks

it seems no apps in stores using it. but it's really simple, and you can implement any widgets.

**Comment by neiljaywarner** [comment]
your general info says "I work for an e-commerce company. We need to build flexible pages." and mentions specifically info about dynamic updates via pushing json from the server.
1) can you say what e-commerce company you work for and/or link to the app in app store that uses this library please
2) Do you feel it makes a viable alternative to codepush?  It seems like it would except of course for bugfix, codepush can fix bugs...

**Comment by dengyin2000** [comment]
> your general info says "I work for an e-commerce company. We need to build flexible pages." and mentions specifically info about dynamic updates via pushing json from the server.
> 
> 1. can you say what e-commerce company you work for and/or link to the app in app store that uses this library please
> 2. Do you feel it makes a viable alternative to codepush?  It seems like it would except of course for bugfix, codepush can fix bugs...

1.  We have not used flutter in our project yet, but we used a similar solution for our native android/ios project. You can search "唯品会" in appstore.

2. It's not for bugfix, because it can't contain any logic code. it's a light ui protocol. It can make you change your app's UI dynamically, and you don't need to republish your app in appstore.
