### ISSUE TITLE
Goto Page on click event

### ISSUE THREAD

**Issue by socialpixe** [dengyin2000/dynamic_widget#43]
Hello, i am using click event, but unable to understand how can i open specific page by check route params ?

route://userDetails?userid=123

Want to goto user details page and read 123

**Comment by dengyin2000** [comment]
You should create a click listener for handling jumping pages.

`class DefaultClickListener implements ClickListener{
  @override
  void onClicked(String event) {
    print("Receive click event: " + event);
  }

}`
