### ISSUE TITLE
is it a dynamic DSL solution?

### ISSUE THREAD

**Issue by Alvazz** [dengyin2000/dynamic_widget#46]
Hi, Dengyin.

Thanks for shared good project.

Has one question.

Does this have any relevance to JS? In other words, is it a dynamic DSL solution?

**Comment by dengyin2000** [comment]
no, it's a json data definition for each flutter widget.

**Comment by Alvazz** [comment]
so, 
Is it a static solution mentioned in this article?

[Is it a static solution mentioned in this article?
](url)

**Comment by dengyin2000** [comment]
you can push the json to your app, so the UI can be dynamic, Flap is more complicated then dynamic widget, it can execute business logic, but dynamic widget can't

**Comment by Alvazz** [comment]
extremely! so, this is what i want ask. what is it execute business logic principle. thanks

**Comment by Alvazz** [comment]
and one more question.

The business logic execution you are referring to, is it for example, I have a button in the json file, and the event of this button is triggered? Does business logic refer to this event? Or is it something more complicated, for example?

**Comment by dengyin2000** [comment]
dynamic widget is used for dynamic UI, and it supports simple click event, you need handle it by your app dart code.

the usual sence is e-commerce app, which need flexible page. most of click event will route to a product detail page.

**Comment by Alvazz** [comment]
thanks a lot.
