### ISSUE TITLE
Any plans to update to null safety?

### ISSUE THREAD

**Issue by princestha** [dengyin2000/dynamic_widget#59]
Hi, amazing package. Love what you are doing. 

Just wondering, any plans to update the package to null safety? 

Thank you

**Comment by dengyin2000** [comment]
> Hi, amazing package. Love what you are doing.
> 
> Just wondering, any plans to update the package to null safety?
> 
> Thank you

yes, I will make it support null safety soon.

**Comment by dengyin2000** [comment]
null safety version was released, please check https://pub.dev/packages/dynamic_widget/versions/4.0.0-nullsafety.1

**Comment by princestha** [comment]
Thank you
