### ISSUE TITLE
Flare-Flutter Support ! [enhancement]

### ISSUE THREAD

**Issue by LOG-TAG** [dengyin2000/dynamic_widget#6]
it will be great if we get the Flare support 

```
Widget build(BuildContext context) {
    return new FlareActor("animations/boring_star.flr",
        alignment: Alignment.center,
        fit: BoxFit.contain,
        animation: "rotate_scale_color");
  }
```

**Comment by dengyin2000** [comment]
> it will be great if we get the Flare support
> 
> ```
> Widget build(BuildContext context) {
>     return new FlareActor("animations/boring_star.flr",
>         alignment: Alignment.center,
>         fit: BoxFit.contain,
>         animation: "rotate_scale_color");
>   }
> ```

you can implement it by yourself easily. https://github.com/dengyin2000/dynamic_widget#how-to-implement-a-widgetparser
