### ISSUE TITLE
A Material Design "raised button" is deprecated.

### ISSUE THREAD

**Issue by MrDeeKey** [dengyin2000/dynamic_widget#66]
RaisedButton class is deprecated, please add ElevatedButton into the package for consistency.

**Comment by dengyin2000** [comment]
> RaisedButton class is deprecated, please add ElevatedButton into the package for consistency.

please check ver 4.0.1

**Comment by MrDeeKey** [comment]
Oh, cool, I'll try it later :) Thx!
