### ISSUE TITLE
Selectabletextwidget

### ISSUE THREAD

**Issue by laurent1956** [dengyin2000/dynamic_widget#71]
How can I use the recognizer in Selectabletextwidget: TapGestureRecognizer()
.. onTap = () {
listener!. onClicked(clickEvent);
},
and then write it to the JSON file

**Comment by dengyin2000** [comment]
please try

`
var textSpanJson = '''
{
  "type": "Container",
  "color": "#FF00FF",
  "alignment": "center",
  "child": {
    "type": "Text",
    "maxLines": 3,
    "textSpan": {
      "text": "Flutter",
      "style": {
        "color": "#00FFFF",
        "fontSize": 26.0
      },
      "recognizer": "route://productDetail?goods_id=123",
      "children": [
        {
          "text": " dynamic",
          "style": {
            "fontSize": 22.0
          }
        },
        {
          "text": " widget",
          "style": {
            "color": "#00FF00",
            "fontSize": 18.0
          }
        }
      ]
    }
  }
}


''';
`

**Comment by laurent1956** [comment]
![image](https://user-images.githubusercontent.com/32734457/130494650-2b3224db-74aa-41af-83d5-f1f71cb6e099.png)
Thanks for your response 
but im not  become  an event response 
see hardcopy

**Comment by laurent1956** [comment]
Thanks for your response
can i start a action with the event 
for exemple a api call ?

**Comment by dengyin2000** [comment]
> Thanks for your response
> can i start a action with the event 
> for exemple a api call ?

You should do it in clicklinster.
