### ISSUE TITLE
AssetImage

### ISSUE THREAD

**Issue by laurent1956** [dengyin2000/dynamic_widget#72]
When i start a test with AssetImage 
i have a error 
Null safety ? 
![image](https://user-images.githubusercontent.com/32734457/130498943-f345b9b1-032b-4973-8cd7-1c1d9f7e80e4.png)

**Comment by dengyin2000** [comment]
it seems you should define the name field in your json string, show me your json string.

**Comment by laurent1956** [comment]
{
        "type": "AssetImage",
        "width": 100,
        "src": "info.jpg"
      }

**Comment by dengyin2000** [comment]
please check AssetImage's widget document, https://github.com/dengyin2000/dynamic_widget/blob/master/WIDGETS.md#assetimage-widget

you should replace "src" with "name". like this.

{
"type": "AssetImage",
"width": 100,
"name": "info.jpg"
}

**Comment by laurent1956** [comment]
its OK 
thx for help
