### ISSUE TITLE
Flutter 2.10.2 renamed pie_chart_outlined to pie_chart_outline

### ISSUE THREAD

**Issue by abner** [dengyin2000/dynamic_widget#87]
Flutter 2.10.2 renamed pie_chart_outlined to pie_chart_outline and so the build fails if I use the dynamic_widget as a dependency on my projects

**Comment by abner** [comment]
Flutter 2.10.2 renamed pie_chart_outlined to pie_chart_outline and so the build fails if I use the dynamic_widget as a dependency on my projects

**Comment by NassB** [comment]
You have to change the name of the icon in the icons_helper.dart file while waiting for the fix

**Comment by Maxmontgelas** [comment]
Please fix this

**Comment by abner** [comment]
This pull request  #89 from @zhangruiyu  fixes this

**Comment by tomassilgueira** [comment]
@dengyin2000 please checkout this

**Comment by dengyin2000** [comment]
> @dengyin2000 please checkout this

merged by other pr

**Comment by prilepskiy** [comment]
Sorry, I still get this error with dynamic_widget 4.0.4 and flutter 2.10.4. How I can fix that?
