### ISSUE TITLE
 editable forms - click event and logic

### ISSUE THREAD

**Issue by gedw99** [dengyin2000/dynamic_widget#9]
I would like to do a post back and collect form data in the widget.

SO this means databinding from the value of the widget to a JSON or name value array and then adding that to the URL as a payload.

this would allow editable forms

**Comment by dengyin2000** [comment]
> I would like to do a post back and collect form data in the widget.
> 
> SO this means databinding from the value of the widget to a JSON or name value array and then adding that to the URL as a payload.
> 
> this would allow editable forms

I think this library is not suitable for your scene, it is for displaying UI dynamically.

**Comment by gedw99** [comment]
https://github.com/neohelden/Flutter-AdaptiveCards

This does allow postback of data.
