### ISSUE TITLE
4.0.4 error with Pie_chart_outlined / pie_chart_outline

### ISSUE THREAD

**Issue by curregoz** [dengyin2000/dynamic_widget#91]
Hi. I got a problem running my app after upgraded to Flutter 2.10.4.

`../../flutter/.pub-cache/hosted/pub.dartlang.org/dynamic_widget-4.0.4/lib/dynamic_widget/icons_helper.dart:742:31: Error: Member not found: 'pie_chart_outlined'.
  'pie_chart_outlined': Icons.pie_chart_outlined,
                              ^^^^^^^^^^^^^^^^^^`

I checked the #89 and this issue is already solved but i don't know why the error persist.

I'm using 4.0.4 version

`dynamic_widget: 4.0.4`

**Icon_Helper.dart of pub version**
line 742: `'pie_chart_outlined': Icons.pie_chart_outlined,`

**Icon_Helper.dart of repository version**
line 742:  `'pie_chart_outline': Icons.pie_chart_outline,`

Flutter Doctor

`[✓] Flutter (Channel stable, 2.10.4, on macOS 12.1 21C52 darwin-arm, locale en-CO)
    • Flutter version 2.10.4 at /Users/cesarurrego/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (4 weeks ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/cesarurrego/Development/Android/SDK
    • Platform android-32, build-tools 32.1.0-rc1
    • ANDROID_HOME = /Users/cesarurrego/Development/Android/SDK
    • ANDROID_SDK_ROOT = /Users/cesarurrego/Development/Android/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.66.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-                       • android-arm64  • Android 12 (API 31) (emulator)
    • iPhone 13 mini (mobile)     • 6C417FAC • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-4 (simulator)
    • Chrome (web)                • chrome                               • web-javascript • Google Chrome 100.0.4

[✓] HTTP Host Availability
    • All required HTTP hosts are available
`

**Comment by dheerajv09** [comment]
I am also facing this issue

**Comment by KlausJokisuo** [comment]
This issue is fixed with https://github.com/dengyin2000/dynamic_widget/commit/ff1b45f315af8f777cbbd5cda8496fb9131d1fd9

You can use the latest master or wait for @dengyin2000 to make a new release.
